config/routes.rb
Rails.application.routes.draw do

resources :users_admins

  
 resources :shopping_carts
 resources :shopping_cart
   devise_for :users 
  resources :categories 
  resources :books do
     resources :order_items
      end
 

devise_scope :user do
  get 'users/sign_out' => "devise/sessions#destroy"
   get 'users' => 'devise/registrations#new'
end

  root 'categories#index'

  post 'shopping_carts/:id' => 'shopping_carts#adddd'
 
  get 'shopping_carts/quantity' => 'shopping_carts#quantity'
   
   get 'shopping_carts/check/:id' => 'shopping_carts#check'
   get 'shopping_carts/remove_item' => 'shopping_carts#remove_item'
   get 'shopping_cart_itemss/get_items' => 'shopping_cart_items#get_items'
   get 'devise/categories' => 'categories#index'
   get'devise/shopping_cart_items/get_items' => 'shopping_cart_items#get_items'
   get 'books/:id/upvote'  => 'books#upvote'
   get 'books/:id/downvote'  => 'books#downvote'
   get 'shopping_cart_items/all_orders' => 'shopping_cart_items#all_orders'
   get'devise/shopping_carts/show' =>'shopping_carts#show'

   match ':controller(/:action(/:id))', :via => :get
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

load_and_authorize_resource

 def get_books

  @bookk= Book.where(:category_id  => params[:id])

  end
 helper_method :get_books
 

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_name %><br>
    <%= f.text_field :category_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/get_books.html.erb
<%if notice %>
<p id="notice" style="margin-top:10px;margin-left:20px;width:250px" class="alert alert-success" role="alert"><%= notice %></p>
<%end%>

<h1>Listing bookss</h1>

<table>
  <thead>
    <tr>
      <th>books name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookk.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.id %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_book_path %>

app/views/categories/index.html.erb
<%if notice %>
<p id="notice" style="margin-top:10px;margin-left:20px;width:250px" class="alert alert-success" role="alert"><%= notice %></p>
<%end%>

<%if signed_in?%>
 <% if current_user.admin?  %>
 <h1>Listing Categories</h1>
<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>
<%else %>


  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
           
            
         <!--  <li> <%= link_to "Home", {:controller => 'categories', :action => 'index'} %> </li> -->
        
       <% @categories.each do |category| %>
      
        <li><%= link_to category.category_name, category %></li>
     
    <% end %>
          </ul>
     
          
        </div>
         <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
  <ul style="margin-left:300px; margin-top:10px">
 
    <% Book.all.each do |book| %>
   <li class="list"> 
    

     <!-- <img src="/assets/<%=book.image%> " width="200" height="200"/> --> <%= link_to (  image_tag book.imagee.url, :size => '200x200') ,book%> </br> <%= link_to book.name, book %></br><%= number_to_currency book.price , unit: "L.E "%> <%= render 'shopping_carts/form', :book_id => book.id, :a =>0 %>  </li>  
   
    <% end %>
   </ul>
  <% end %>
  <%else %>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
           
            
         <!--  <li> <%= link_to "Home", {:controller => 'categories', :action => 'index'} %> </li> -->
        
       <% @categories.each do |category| %>
      
        <li><%= link_to category.category_name, category %></li>
     
    <% end %>
          </ul>
     
          
        </div>
         <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
  <ul style="margin-left:300px; margin-top:10px">
 
    <% Book.all.each do |book| %>
   <li class="list"> 
    

     <!-- <img src="/assets/<%=book.image%> " width="200" height="200"/> --> <%= link_to (  image_tag book.imagee.url, :size => '200x200') ,book%> </br> <%= link_to book.name, book %></br><%= number_to_currency book.price , unit: "L.E "%> <%= render 'shopping_carts/form', :book_id => book.id, :a =>0 %>  </li>  
   
    <% end %>
   </ul>
  <%end%>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%if notice %>
<p id="notice" style="margin-top:10px;margin-left:20px;width:250px" class="alert alert-success" role="alert"><%= notice %></p>
<%end%>


<%if signed_in?%>
   <% if current_user.admin?  %>
 </br></br></br></br></br>
   <p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>
<ul >
         
     </br>
 
    <% get_books.each do |book| %>
   <li > 
   <%= link_to 'Show', book %>
     <%= link_to 'Edit', edit_book_path(book) %>
    <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= book.name %> 
   <%= book.price %> </li>  
    
    <% end %>
   </ul>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> |
<%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' } %>
<%else%>
 <body >

    

    <div class="container-fluid">
      <div class="row" >
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
           
      <%  @categoriess= Category.all %>
       <% @categoriess.each do |category| %>
      
        <li><%= link_to category.category_name, category %></li>
     
    <% end %>
          </ul>
     
          
        </div>
         <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>

  
  <ul style="margin-left:300px; margin-top:200px">
          <em><h1 style="margin-left:300px; margin-top:-150px;color:#5a7032">
   <%= @category.category_name %></h1></em>
     </br>
 
    <% get_books.each do |book| %>
   <li class="list"> 
    <%= link_to (  image_tag book.imagee.url, :size => '200x200') ,book%>

    <!--  <img src="/assets/<%=book.image%> " width="200" height="200"/>  --></br> <%= link_to book.name, book %></br><%= number_to_currency book.price , unit: "L.E "%> <%= render 'shopping_carts/form', :book_id => book.id, :a =>0 %>  </li>  
   
    <% end %>
   </ul>
    <%end%>
    <%else%>
    <body >

    

    <div class="container-fluid">
      <div class="row" >
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
           
      <%  @categoriess= Category.all %>
       <% @categoriess.each do |category| %>
      
        <li><%= link_to category.category_name, category %></li>
     
    <% end %>
          </ul>
     
          
        </div>
         <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>

  
  <ul style="margin-left:300px; margin-top:200px">
          <em><h1 style="margin-left:300px; margin-top:-150px;color:#5a7032">
   <%= @category.category_name %></h1></em>
     </br>
 
    <% get_books.each do |book| %>
   <li class="list"> 
    <%= link_to (  image_tag book.imagee.url, :size => '200x200') ,book%>

    <!--  <img src="/assets/<%=book.image%> " width="200" height="200"/>  --></br> <%= link_to book.name, book %></br><%= number_to_currency book.price , unit: "L.E "%> <%= render 'shopping_carts/form', :book_id => book.id, :a =>0 %>  </li>  
   
    <% end %>
   </ul>
    <%end%>