config/routes.rb
Rails.application.routes.draw do

resources :users_admins

  
 resources :shopping_carts
 resources :shopping_cart
   devise_for :users 
  resources :categories 
  resources :books do
     resources :order_items
      end
 

devise_scope :user do
  get 'users/sign_out' => "devise/sessions#destroy"
   get 'users' => 'devise/registrations#new'
end

  root 'categories#index'

  post 'shopping_carts/:id' => 'shopping_carts#adddd'
 
  get 'shopping_carts/quantity' => 'shopping_carts#quantity'
   
   get 'shopping_carts/check/:id' => 'shopping_carts#check'
   get 'shopping_carts/remove_item' => 'shopping_carts#remove_item'
   get 'shopping_cart_itemss/get_items' => 'shopping_cart_items#get_items'
   get 'devise/categories' => 'categories#index'
   get'devise/shopping_cart_items/get_items' => 'shopping_cart_items#get_items'
   get 'books/:id/upvote'  => 'books#upvote'
   get 'books/:id/downvote'  => 'books#downvote'
   get 'shopping_cart_items/all_orders' => 'shopping_cart_items#all_orders'
   get'devise/shopping_carts/show' =>'shopping_carts#show'

   match ':controller(/:action(/:id))', :via => :get
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= render 'shared/navbar' %>

<%= yield %>

</body>
</html>